services:
  summit_db:
    build: summit_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: enextremtrandomstringmedflertalettecken
      POSTGRES_DB: summit_db
    ports:
      - "5432:5432"
    volumes:
      - summit_database_data:/var/lib/postgresql/data
  
  summit_web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env

volumes:
  summit_database_data:
