services:
  summit_web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - summit_uploads:/data/uploads
    depends_on: 
      summit_db:
        condition: service_healthy
    restart: on-failure
    environment:
      ACTIVE_GROUPS_WHITELIST: b7ab170f-712d-40b0-9ed0-aca9bde07a61,9adae6f5-58cd-4c14-aa6f-caaecfe98402,dea3493e-66e4-44b2-a657-cb57a6840dab

  summit_db:
    build: summit_database
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - summit_database_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  gotify:
    image: cthit/gotify:latest
    environment:
      GOTIFY_PRE-SHARED-KEY: "123abc"
      GOTIFY_MOCK-MODE: "true"
      GOTIFY_DEBUG-MODE: "true"
      GOTIFY_GOOGLE-MAIL.KEYFILE: "/app/gapp.json"
      GOTIFY_GOOGLE-MAIL.ADMIN-MAIL: "admin@chalmers.it"
    volumes:
      - ./gapp.json:/app/gapp.json:ro,z
    ports:
      - 8080:8080

volumes:
  summit_database_data:
  summit_uploads:
