@startchen data_base_diagram

entity "Document" as Doc {
    document_name : STRING
    file_path : STRING
}

entity "Läsperiod" as StudyPeriod {
    year : INT
    period : INT
}

entity "Meeting" as Meeting {
    id : uuid
    date : timestamp
}

@endchen